djangostreetmap/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import (
    Aeroways,
    BuildingPolygon,
    ExampleMapView,
    Hospitals,
    LandLayer,
    MapStyle,
    PoiLayer,
    Roads,
)

app_name = "djangostreetmap"

urlpatterns = [
    # path("highways/<int:zoom>/<int:x>/<int:y>.pbf", cache_page(60 * 15)(RoadLayerView.as_view()), name="highways"),
    # path("admboundary/<int:zoom>/<int:x>/<int:y>.pbf", cache_page(60 * 15)(AdminBoundaryLayerView.as_view()), name="admin"),
    # path("islands/<int:zoom>/<int:x>/<int:y>.pbf", cache_page(60 * 15)(IslandsAreaLayerView.as_view()), name="islands"),
    # path("facebookai/<int:zoom>/<int:x>/<int:y>.pbf", cache_page(60 * 15)(FacebookAiLayerView.as_view()), name="facebookai"),
    path("example_map", ExampleMapView.as_view()),
    # These allow maps to make reverse URL calls a little easier
    # path("highways/", RoadLayerView.as_view(), name="highways"),
    # path("admboundary/", AdminBoundaryLayerView.as_view(), name="admin"),
    # path("islands/", IslandsAreaLayerView.as_view(), name="islands"),
    # path("facebookai/", FacebookAiLayerView.as_view(), name="facebookai"),
    path("buildings/", BuildingPolygon.as_view(), name="buildings"),
    path("buildings/<int:zoom>/<int:x>/<int:y>.pbf", cache_page(60 * 15)(BuildingPolygon.as_view()), name="buildings"),
    path("roads/", Roads.as_view(), name="roads"),
    path("roads/<int:zoom>/<int:x>/<int:y>.pbf", cache_page(60 * 15)(Roads.as_view()), name="roads"),
    path("hospitals", Hospitals.as_view(), name="hospitals"),
    path("airports", Aeroways.as_view(), name="aeroways"),
    path("land/", cache_page(60 * 15)(LandLayer.as_view()), name="land"),
    path("land/<int:zoom>/<int:x>/<int:y>.pbf", cache_page(60 * 15)(LandLayer.as_view()), name="land"),
    path("poi/", cache_page(60 * 15)(PoiLayer.as_view()), name="poi"),
    path("poi/<int:zoom>/<int:x>/<int:y>.pbf", cache_page(60 * 15)(PoiLayer.as_view()), name="poi"),
    path("style", MapStyle.as_view(), name="map_style"),
]

djangostreetmap/models.py
from django.contrib.gis.db.models.fields import MultiPolygonField
from django.db import models


class SimplifiedLandPolygon(models.Model):
    """
    This is a "simplified polygons" layer from OSM
    """

    geom = MultiPolygonField(srid=3857)

djangostreetmap/views.py
import hashlib
import logging
from dataclasses import asdict
from typing import Any, Dict, List, Optional, Sequence, Tuple, Type, Union

from django.apps import apps
from django.contrib.gis.db.models.functions import Centroid, Transform
from django.db import connection
from django.db.models import Model
from django.http import HttpRequest, JsonResponse
from django.http.response import HttpResponse
from django.urls import reverse
from django.views import View
from django.views.generic.base import TemplateView
from osmflex.models import AmenityPoint, OsmLine, OsmPoint, OsmPolygon, RoadLine
from psycopg2 import sql

from djangostreetmap import models
from djangostreetmap.annotations import (
    GeoJsonSerializer,
    MultiGeoJsonSerializer,
    TileCache,
)
from djangostreetmap.functions import AsFeatureCollection, Intersects
from djangostreetmap.tilegenerator import MvtQuery, Tile
from maplibre import layer, sources
from maplibre.basemodel import Root
from maplibre.layer import Layer as L

from .timer import Timer

logger = logging.getLogger(__name__)


class ExampleMapView(TemplateView):
    template_name = "leaflet_tile_layers.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["map_view"] = "[-8.556416, 125.5524171], 14"
        return context


class TileLayerView(View):
    """
    Handle generation and views of tile layers
    For urls.py you likely want two entries for easier reversing in templates
    >>> path("mylayer/<int:zoom>/<int:x>/<int:y>.pbf", MyTileLayerView.as_view()), name="mylayer"),
    >>> path("mylayer", MyTileLayerView.as_view(), name="mylayer"),
    """

    layers: List[MvtQuery] = []
    tilecache: Optional[TileCache] = None

    def get_layers(self, tile: Tile) -> List[MvtQuery]:
        """
        Override for dynamically determining tile content
        based on tile properties (most likely zoom)
        """
        return self.layers

    def _generate_tile(self, tile: Tile) -> List[bytes]:

        params = asdict(tile)

        with connection.cursor() as cursor:
            tiles: List[bytes] = []
            for query_layer in self.get_layers(tile):
                params.update(query_layer.query_params)
                query = query_layer.as_mvt()
                # Uncomment to see the SQL which is run
                # logger.info(query.as_string(cursor.cursor))
                with Timer(name="tile generator", logger=logger.info):
                    tile_response: Optional[Sequence] = None
                    key: Optional[str] = None

                    if self.tilecache:
                        key = hashlib.sha256(f"{query}, {params}".encode()).hexdigest()[:8]

                    if self.tilecache and key:
                        content_bytes: Optional[bytes] = self.tilecache.get(key)
                        if content_bytes is not None:
                            logger.info("Cached tile returning")
                            tiles.append(content_bytes)
                            continue
                        logger.info("No tile cached")

                    try:
                        cursor.execute(query, params)  # type: ignore
                        tile_response = cursor.fetchone()
                    except Exception as E:
                        logger.error(f"{E}")
                        logger.info(query.as_string(cursor.cursor))
                    if not tile_response:
                        continue
                    content: memoryview = tile_response[0]
                    new_content_bytes: bytes = content.tobytes()
                    if new_content_bytes:
                        tiles.append(new_content_bytes)

                    if self.tilecache and key:
                        self.tilecache.set(key, new_content_bytes)

            return tiles

    def get(self, request: HttpRequest, *args, **kwargs):
        with Timer(name="tile get", logger=logger.info):
            tile = Tile(**kwargs)  # Expect to receive zoom, x, and y in kwargs
            tiles = b"".join(self._generate_tile(tile))
            return HttpResponse(content=tiles, content_type="application/binary")


class BuildingPolygon(TileLayerView):
    def get_layers(self, tile: Tile):

        if tile.zoom < 14:
            return []

        return [
            MvtQuery(
                table="osmflex_buildingpolygon",
                attributes=["name", "osm_id", "osm_subtype"],
                calculated_attributes={"render_min_height": sql.SQL('COALESCE("height", "levels" * 4, 4)')},
                layer="buildings",
                pk="osm_id",
            )
        ]


class Roads(TileLayerView):
    def get_layers(self, tile: Tile):

        road_osm_types = [
            ("trunk", 2),
            ("steps", 12),
            ("road", 12),
            ("footway", 12),
            ("secondary", 7),
            ("tertiary", 9),
            ("secondary_link", 7),
            ("tertiary_link", 9),
            ("living_street", 12),
            ("pedestrian", 12),
            ("primary", 5),
            ("residential", 13),
            ("primary_link", 5),
            ("track", 12),
            ("motorway_link", 12),
            ("motorway", 5),
            ("service", 12),
            ("unclassified", 12),
            ("path", 12),
        ]  # type: List[Tuple[str, int]]

        # Determine which road types to include in the layer

        type_filter = sql.SQL("""{field} = ANY(ARRAY[{types}]::text[])""").format(
            field=sql.Identifier("osm_type"), types=sql.SQL(",").join([sql.Literal(rt) for rt, mz in road_osm_types if tile.zoom > mz])
        )

        roads = MvtQuery(
            table=RoadLine._meta.db_table,
            attributes=["name", "osm_type"],
            filters=[type_filter],
            layer="transportation",
            transform=False,
            pk="osm_id",
        )

        return [roads]


class Hospitals(View):
    def get(self, request: HttpRequest, *args, **kwargs):
        AmenityPoint = apps.get_model("osmflex", "AmenityPoint")
        AmenityPolygon = apps.get_model("osmflex", "AmenityPolygon")

        points = AmenityPoint.objects.filter(osm_type__in=["hospital", "clinic"]).annotate(geom_for_json=Transform("geom", 4326))
        centroids = AmenityPolygon.objects.filter(osm_type__in=["hospital", "clinic"]).annotate(geom_centroid=Transform(Centroid("geom"), 4326))

        response = MultiGeoJsonSerializer(
            [
                GeoJsonSerializer(points, "geom_for_json", ("name", "osm_type", "address")),
                GeoJsonSerializer(centroids, "geom_centroid", ("name", "osm_type", "address")),
            ]
        )

        return JsonResponse(data=asdict(response.to_collection()), content_type="application/json")


class Aeroways(View):
    def get(self, request: HttpRequest, *args, **kwargs):
        point = apps.get_model("osmflex", "InfrastructurePoint")
        polygon = apps.get_model("osmflex", "InfrastructurePolygon")

        points = point.objects.filter(osm_type__in=["aeroway"]).annotate(geom_for_json=Transform("geom", 4326))
        centroids = polygon.objects.filter(osm_type__in=["aeroway"]).annotate(geom_centroid=Transform(Centroid("geom"), 4326))

        response = MultiGeoJsonSerializer(
            [
                GeoJsonSerializer(points, "geom_for_json", ("name", "osm_type")),
                GeoJsonSerializer(centroids, "geom_centroid", ("name", "osm_type")),
            ]
        )

        return JsonResponse(data=asdict(response.to_collection()), content_type="application/json")


class LandLayer(TileLayerView):
    layers = [MvtQuery(table=models.SimplifiedLandPolygon._meta.db_table, layer="land")]


class PoiLayer(TileLayerView):
    layers = [
        MvtQuery(
            table=AmenityPoint._meta.db_table,
            attributes=["name"],
            # filters = sql.SQL("{} = {}").format(sql.Identifier("osm_type"), sql.Literal("school")),
            layer="school",
            pk="osm_id",
        )
    ]


class ModelFeatureCollectionView(View):
    """
    Container for OSM layer data
    """

    class Meta:
        proxy = True

    def geojson(
        self,
        model: Union[OsmPoint, OsmLine, OsmPolygon],
        filter_kwargs: Dict[str, Any],
        intersect: Type[Model],  # Note that we make some assumptions about "intersect" model here, see "Intersect" class
        **kwargs,
    ):
        """
        Returns a FeatureCollection of instances from "model" where the geometry
        intersects the area represented by this location profile

        For instance

        >>> OpenStreetMapData.objects.get(area__name="Highlands 1").geojson(AmenityPoint, osm_type="school")
        """
        # The OSM data import is in 3857. We transform to the geom of the
        # surrounding geometry, if applicable
        queryset = model.objects.all().annotate(geom_t=Transform("geom", 4326))
        queryset = queryset.annotate(in_area=Intersects(intersect)).filter(in_area=True)
        queryset = queryset.filter(**filter_kwargs)

        attributes = {field.name: field.name for field in model._meta.fields if field.name != "geom"}
        return queryset.aggregate(_=AsFeatureCollection("geom_t", **attributes))["_"]


class MapStyle(View):
    """
    Return a simple "mapbox"
    JSON view
    """

    def get(self, request: HttpRequest, *args, **kwargs):

        font = ["Roboto Regular"]
        # map = Root()
        road_source = sources.Vector(type="vector", tiles=[f"{request.scheme}://{request.get_host()}{reverse('djangostreetmap:roads')}{{z}}/{{x}}/{{y}}.pbf"])
        land_source = sources.Vector(type="vector", tiles=[f"{request.scheme}://{request.get_host()}{reverse('djangostreetmap:land')}{{z}}/{{x}}/{{y}}.pbf"])
        poi_source = sources.Vector(type="vector", tiles=[f"{request.scheme}://{request.get_host()}{reverse('djangostreetmap:poi')}{{z}}/{{x}}/{{y}}.pbf"])

djangostreetmap/templates/leaflet_tile_layers.html
<html>
    <head>
        <link
            rel="stylesheet"
            href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
            integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
            crossorigin=""
        />
        <script
            src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
            integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
            crossorigin=""
        ></script>
        <script type="text/javascript" src="https://unpkg.com/leaflet.vectorgrid@1.2.0"></script>
    </head>
    <body>
        <div id="mapid" style="width: 1800px; height: 1000px; background:#aad3df"></div>
        <script>
            const mymap = L.map("mapid", {preferCanvas: true}).setView({{map_view}});

            function getHospitals(){
                const onEachFeature = (feature, layer) => {
                    layer.bindPopup(`<b>${feature.properties.name}</b> ${feature.properties.osm_type}`);
                }
                const layer = fetch("{% url 'djangostreetmap:hospitals' %}")
                    .then(response => response.json())
                    .then(data => L.geoJSON(data, {onEachFeature:onEachFeature}))
                return layer
            }
            function getAeroways(){
                const onEachFeature = (feature, layer) => {
                    layer.bindPopup(`<b>${feature.properties.name}</b> ${feature.properties.osm_type}`);
                }
                const layer = fetch("{% url 'djangostreetmap:aeroways' %}")
                    .then(response => response.json())
                    .then(data => L.geoJSON(data, {onEachFeature:onEachFeature}))
                return layer
            }

            function getOsm(){
                const osmUrl = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
                const osmAttrib = 'Map data © <a href="https://openstreetmap.org">OpenStreetMap</a> contributors';

                // Layer
                return new L.TileLayer(osmUrl, {
                    minZoom: 4,
                    maxZoom: 20,
                    attribution: osmAttrib
                });
            }

            /* Add an openlayers */

            // Data provider


            const building_opts = {
                // interactive: true,
                vectorTileLayerStyles: {
                    buildings: function(properties, zoom){
                        return {radius: 5, weight: 0.5, color: "gray"};
                    },
                    building_point: function(){debugger; return {radius: 1, color: "gray"}}
                }
            }

            const road_opts = {
                // interactive: true,
                vectorTileLayerStyles: {
                    trunk: {weight: 2, color: "red"},
                    roads: {weight: 2, color: "red"},
                    secondary: function(properties, zoom){
                        const c = '#f7fabf';
                        if (zoom < 6){ return {weight: 1, color: c} };
                        if (zoom < 10){ return {weight: 3, color: c} };
                        return {weight: 5, color: c}
                    },
                    trunk_link: {weight: 2, color: "red"},
                    tertiary: function(properties, zoom){
                        const c = '#ffffff';
                        if (zoom < 6){ return {weight: 1, color: c} };
                        if (zoom < 10){ return {weight: 2, color: c} };
                        return {weight: 3, color: c}
                    },
                    secondary_link: function(properties, zoom){
                        const c = '#f7fabf';
                        if (zoom < 6){ return {weight: 1, color: c} };
                        if (zoom < 10){ return {weight: 2, color: c} };
                        return {weight: 4, color: c}
                    },
                    tertiary_link: function(properties, zoom){
                        const c = '#ffffff';
                        if (zoom < 6){ return {weight: 1, color: c} };
                        if (zoom < 10){ return {weight: 3, color: c} };
                        return {weight: 5, color: c}
                    },
                    primary: function(properties, zoom){
                        const c = '#fcd6a4';
                        if (zoom < 6){ return {weight: 1, color: c} };
                        if (zoom < 10){ return {weight: 3, color: c} };
                        return {weight: 5, color: c}
                    },
                    residential: {weight: 2, color: "gray"},
                    primary_link: function(properties, zoom){
                        const c = '#fcd6a4';
                        if (zoom < 6){ return {weight: 1, color: c} };
                        if (zoom < 10){ return {weight: 3, color: c} };
                        return {weight: 5, color: c}
                    },
                    track: {weight: 1, color: "white"},
                    service: {weight: 1, color: "white"},
                    unclassified: {weight: 1, color: "white"},
                    path: {weight: 0.5, color: "white"},
                }
            }

            const opts = {
                interactive: true,
                vectorTileLayerStyles: {
                    admin_boundary: {
                        weight: 2,
                        color: "#cdbcc9",
                        fillColor: "#f2efe9",
                        fillOpacity: 1,
                        fill: true
                    },
                    islands: {
                        weight: 1,
                        color: "#cdbcc9",
                        fillColor: "#f2efe9",
                        fillOpacity: 1,
                        fill: true
                    }
                }
            };


                const buildings = L.vectorGrid
                .protobuf("{% url 'djangostreetmap:buildings' %}{z}/{x}/{y}.pbf", building_opts)
                // .on("mouseover", function (e) {
                //     L.popup()
                //         .setContent(`Name: ${e.layer.properties.name}, type: ${e.layer.properties.highway}`)
                //         .setLatLng(e.latlng)
                //         .openOn(mymap);
                //     L.DomEvent.stop(e);
                // })
                .addTo(mymap);

                const osmLayer = getOsm();
                osmLayer.addTo(mymap);
                // const roads = L.vectorGrid
                // .protobuf("{% url 'djangostreetmap:roads' %}{z}/{x}/{y}.pbf", road_opts)
                // .on("mouseover", function (e) {
                //     L.popup()
                //         .setContent(`Name: ${e.layer.properties.name}, type: ${e.layer.properties.osm_type}`)
                //         .setLatLng(e.latlng)
                //         .openOn(mymap);
                //     L.DomEvent.stop(e);
                // })
                // .addTo(mymap);

                const minor_roads = L.vectorGrid
                .protobuf("{% url 'djangostreetmap:roads' %}{z}/{x}/{y}.pbf", road_opts)
                .on("mouseover", function (e) {
                    L.popup()
                        .setContent(`Name: ${e.layer.properties.name}, type: ${e.layer.properties.osm_type}`)
                        .setLatLng(e.latlng)
                        .openOn(mymap);
                    L.DomEvent.stop(e);
                })
                .addTo(mymap);

                baseMaps = {}

                const control = L.control.layers();
                control.addTo(mymap);

                control.addOverlay(osmLayer, 'osm');
                // control.addOverlay(roads, 'roads');
                control.addOverlay(minor_roads, 'minor_roads');
                control.addOverlay(buildings, 'buildings');
                // getHospitals().then((l) => {l.addTo(mymap); control.addOverlay(l, 'hospitals')} )
                // getAeroways().then((l) => {l.addTo(mymap); control.addOverlay(l, 'aeroways')} )
        </script>
    </body>
</html>

djangostreetmap/templates/ol_tile_layers.html
<html>
    <head>
        <link
            rel="stylesheet"
            href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
            integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
            crossorigin=""
        />
        <script
            src="https://unpkg.com/leaflet@1.7.1/dist/leaflet-src.js"
        ></script>
        <!-- <script type="text/javascript" src="https://unpkg.com/leaflet.vectorgrid@1.2.0"></script>         -->
        <script type="text/javascript" src="https://unpkg.com/leaflet.vectorgrid@1.3.0/dist/Leaflet.VectorGrid.bundled.js"></script>

    </head>
    <body>
        <div id="mapid" style="width: 1800px; height: 1000px; background:#aad3df"></div>
        <script>
            var mymap = L.map("mapid").setView({{map_view}});

            const road_opts = {
                interactive: true,
                vectorTileLayerStyles: {
                    trunk: {weight: 2, color: "red"},
                    road: {weight: 1, color: "white"},
                    secondary: function(properties, zoom){
                        const c = '#f7fabf';
                        if (zoom < 6){ return {weight: 1, color: c} };
                        if (zoom < 10){ return {weight: 3, color: c} };
                        return {weight: 5, color: c}
                    },
                    trunk_link: {weight: 2, color: "red"},
                    tertiary: function(properties, zoom){
                        const c = '#ffffff';
                        if (zoom < 6){ return {weight: 1, color: c} };
                        if (zoom < 10){ return {weight: 2, color: c} };
                        return {weight: 3, color: c}
                    },
                    secondary_link: function(properties, zoom){
                        const c = '#f7fabf';
                        if (zoom < 6){ return {weight: 1, color: c} };
                        if (zoom < 10){ return {weight: 2, color: c} };
                        return {weight: 4, color: c}
                    },
                    tertiary_link: function(properties, zoom){
                        const c = '#ffffff';
                        if (zoom < 6){ return {weight: 1, color: c} };
                        if (zoom < 10){ return {weight: 3, color: c} };
                        return {weight: 5, color: c}
                    },
                    primary: function(properties, zoom){
                        const c = '#fcd6a4';
                        if (zoom < 6){ return {weight: 1, color: c} };
                        if (zoom < 10){ return {weight: 3, color: c} };
                        return {weight: 5, color: c}
                    },
                    residential: {weight: 1, color: "ffffff"},
                    primary_link: function(properties, zoom){
                        const c = '#fcd6a4';
                        if (zoom < 6){ return {weight: 1, color: c} };
                        if (zoom < 10){ return {weight: 3, color: c} };
                        return {weight: 5, color: c}
                    },
                    track: {weight: 1, color: "white"},
                    service: {weight: 1, color: "white"},
                    unclassified: {weight: 1, color: "white"},
                    path: {weight: 0.5, color: "white"},
                }
            }

            const opts = {
                interactive: true,
                vectorTileLayerStyles: {
                    admin_boundary: {
                        weight: 2,
                        color: "#cdbcc9",
                        fillColor: "#f2efe9",
                        fillOpacity: 1,
                        fill: true
                    },
                    islands: {
                        weight: 1,
                        color: "#cdbcc9",
                        fillColor: "#f2efe9",
                        fillOpacity: 1,
                        fill: true
                    }
                }
            };

            const overpass_style = {
                interactive: true,
                vectorTileLayerStyles: {
                 overpass: function(properties, zoom) {
                    return {
                        weight: 2,
                        color: 'red',
                        opacity: 1,
                        fillColor: 'yellow',
                        fill: true,
                        radius: 6,
                        fillOpacity: 0.7
                    }
                },
                    // overpass: {icon: new L.Icon.Default()}
                }
            };

            // const islands = L.vectorGrid.protobuf("{% url 'djangostreetmap:islands' %}{z}/{x}/{y}.pbf", opts).on("mouseover", function (e) {
            //         L.popup()
            //             .setContent(e.layer.properties.name || e.layer.properties.type)
            //             .setLatLng(e.latlng)
            //             .openOn(mymap);
            //         L.DomEvent.stop(e);
            //     }).addTo(mymap);

            // const adm = L.vectorGrid
            //     .protobuf("{% url 'djangostreetmap:admin' %}{z}/{x}/{y}.pbf", opts)
            //     .on("mouseover", function (e) {
            //         L.popup()
            //             .setContent(e.layer.properties.name || e.layer.properties.type)
            //             .setLatLng(e.latlng)
            //             .openOn(mymap);
            //         L.DomEvent.stop(e);
            //     })
            //     .addTo(mymap);

            // const highways = L.vectorGrid
            //     .protobuf("{% url 'djangostreetmap:highways' %}{z}/{x}/{y}.pbf", road_opts)
            //     .on("mouseover", function (e) {
            //         L.popup()
            //             .setContent(`Name: ${e.layer.properties.name}, type: ${e.layer.properties.highway}`)
            //             .setLatLng(e.latlng)
            //             .openOn(mymap);
            //         L.DomEvent.stop(e);
            //     })
            //     .addTo(mymap);
            // debugger;
            // const overpass = L.vectorGrid
            //     .protobuf("{% url 'djangostreetmap:overpass' %}{z}/{x}/{y}.pbf", overpass_style)
            //     .on("click", function (e) {
            //         L.popup()
            //             .setContent(e.layer.properties.tag)
            //             .setLatLng(e.latlng)
            //             .openOn(mymap);
            //         })
            //     .addTo(mymap);

            fetch("{% url 'djangostreetmap:overpassjson' %}").then( (data) => data.json()).then( (json_data) => L.geoJSON(json_data).addTo(mymap));
        </script>
    </body>
</html>